include ../../../Makefile.inc

# DO NOT DELETE

main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/algebraicEquation/equation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/algebraicEquation/newton.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/algebraicEquation/solver.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/approximation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/iteration.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/iteration.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/approximation.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/algebraicEquation/solver.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/algebraicEquation/equation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/algebraicEquation/newton.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.1/cppNum/derivative.hpp
